// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class List {
    "id": number;
    "title": string;
    "sortOrder": number;
    "isDefault": boolean;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new List instance. */
    constructor($$source: Partial<List> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new List instance from a string or object.
     */
    static createFrom($$source: any = {}): List {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new List($$parsedSource as Partial<List>);
    }
}

export class ListInput {
    "id": number;
    "title": string;

    /** Creates a new ListInput instance. */
    constructor($$source: Partial<ListInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListInput($$parsedSource as Partial<ListInput>);
    }
}

export class ReorderListsInput {
    "orderedIds": number[];

    /** Creates a new ReorderListsInput instance. */
    constructor($$source: Partial<ReorderListsInput> = {}) {
        if (!("orderedIds" in $$source)) {
            this["orderedIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReorderListsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ReorderListsInput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("orderedIds" in $$parsedSource) {
            $$parsedSource["orderedIds"] = $$createField0_0($$parsedSource["orderedIds"]);
        }
        return new ReorderListsInput($$parsedSource as Partial<ReorderListsInput>);
    }
}

export class ReorderTasksInput {
    "listId": number;
    "parentId": number;
    "orderedIds": number[];

    /** Creates a new ReorderTasksInput instance. */
    constructor($$source: Partial<ReorderTasksInput> = {}) {
        if (!("listId" in $$source)) {
            this["listId"] = 0;
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = 0;
        }
        if (!("orderedIds" in $$source)) {
            this["orderedIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReorderTasksInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ReorderTasksInput {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("orderedIds" in $$parsedSource) {
            $$parsedSource["orderedIds"] = $$createField2_0($$parsedSource["orderedIds"]);
        }
        return new ReorderTasksInput($$parsedSource as Partial<ReorderTasksInput>);
    }
}

export class RepeatRule {
    "frequency": string;
    "interval": number;
    "endMode": string;
    "endDate": string;
    "count": number;

    /** Creates a new RepeatRule instance. */
    constructor($$source: Partial<RepeatRule> = {}) {
        if (!("frequency" in $$source)) {
            this["frequency"] = "";
        }
        if (!("interval" in $$source)) {
            this["interval"] = 0;
        }
        if (!("endMode" in $$source)) {
            this["endMode"] = "";
        }
        if (!("endDate" in $$source)) {
            this["endDate"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepeatRule instance from a string or object.
     */
    static createFrom($$source: any = {}): RepeatRule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepeatRule($$parsedSource as Partial<RepeatRule>);
    }
}

export class Task {
    "id": number;
    "listId": number;
    "parentId": number;
    "title": string;
    "details": string;
    "scheduledAt": string;
    "deadlineAt": string;
    "timeZone": string;
    "starred": boolean;
    "starredAt": string;
    "completedAt": string;
    "sortOrder": number;
    "repeat": RepeatRule;
    "repeatSeriesId": number;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("listId" in $$source)) {
            this["listId"] = 0;
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("scheduledAt" in $$source)) {
            this["scheduledAt"] = "";
        }
        if (!("deadlineAt" in $$source)) {
            this["deadlineAt"] = "";
        }
        if (!("timeZone" in $$source)) {
            this["timeZone"] = "";
        }
        if (!("starred" in $$source)) {
            this["starred"] = false;
        }
        if (!("starredAt" in $$source)) {
            this["starredAt"] = "";
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("repeat" in $$source)) {
            this["repeat"] = (new RepeatRule());
        }
        if (!("repeatSeriesId" in $$source)) {
            this["repeatSeriesId"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        const $$createField12_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repeat" in $$parsedSource) {
            $$parsedSource["repeat"] = $$createField12_0($$parsedSource["repeat"]);
        }
        return new Task($$parsedSource as Partial<Task>);
    }
}

export class TaskInput {
    "id": number;
    "listId": number;
    "parentId": number;
    "title": string;
    "details": string;
    "scheduledAt": string;
    "deadlineAt": string;
    "timeZone": string;
    "starred": boolean;
    "repeat": RepeatRule;

    /** Creates a new TaskInput instance. */
    constructor($$source: Partial<TaskInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("listId" in $$source)) {
            this["listId"] = 0;
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("scheduledAt" in $$source)) {
            this["scheduledAt"] = "";
        }
        if (!("deadlineAt" in $$source)) {
            this["deadlineAt"] = "";
        }
        if (!("timeZone" in $$source)) {
            this["timeZone"] = "";
        }
        if (!("starred" in $$source)) {
            this["starred"] = false;
        }
        if (!("repeat" in $$source)) {
            this["repeat"] = (new RepeatRule());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskInput instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskInput {
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repeat" in $$parsedSource) {
            $$parsedSource["repeat"] = $$createField9_0($$parsedSource["repeat"]);
        }
        return new TaskInput($$parsedSource as Partial<TaskInput>);
    }
}

export class Workspace {
    "lists": List[];
    "tasks": Task[];

    /** Creates a new Workspace instance. */
    constructor($$source: Partial<Workspace> = {}) {
        if (!("lists" in $$source)) {
            this["lists"] = [];
        }
        if (!("tasks" in $$source)) {
            this["tasks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Workspace instance from a string or object.
     */
    static createFrom($$source: any = {}): Workspace {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lists" in $$parsedSource) {
            $$parsedSource["lists"] = $$createField0_0($$parsedSource["lists"]);
        }
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField1_0($$parsedSource["tasks"]);
        }
        return new Workspace($$parsedSource as Partial<Workspace>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = RepeatRule.createFrom;
const $$createType2 = List.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Task.createFrom;
const $$createType5 = $Create.Array($$createType4);
