// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FileFilter {
    "displayName": string;
    "pattern": string;

    /** Creates a new FileFilter instance. */
    constructor($$source: Partial<FileFilter> = {}) {
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): FileFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileFilter($$parsedSource as Partial<FileFilter>);
    }
}

export class MessageDialogOptions {
    "type": string;
    "title": string;
    "message": string;
    "buttons"?: string[];
    "defaultButton"?: string;
    "cancelButton"?: string;

    /** Creates a new MessageDialogOptions instance. */
    constructor($$source: Partial<MessageDialogOptions> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageDialogOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageDialogOptions {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("buttons" in $$parsedSource) {
            $$parsedSource["buttons"] = $$createField3_0($$parsedSource["buttons"]);
        }
        return new MessageDialogOptions($$parsedSource as Partial<MessageDialogOptions>);
    }
}

export class OpenFilesOptions {
    "title": string;
    "defaultDirectory"?: string;
    "filters"?: FileFilter[];
    "multiple": boolean;

    /** Creates a new OpenFilesOptions instance. */
    constructor($$source: Partial<OpenFilesOptions> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("multiple" in $$source)) {
            this["multiple"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenFilesOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenFilesOptions {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField2_0($$parsedSource["filters"]);
        }
        return new OpenFilesOptions($$parsedSource as Partial<OpenFilesOptions>);
    }
}

export class SaveFileOptions {
    "title": string;
    "defaultDirectory"?: string;
    "defaultFilename"?: string;
    "filters"?: FileFilter[];

    /** Creates a new SaveFileOptions instance. */
    constructor($$source: Partial<SaveFileOptions> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveFileOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveFileOptions {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField3_0($$parsedSource["filters"]);
        }
        return new SaveFileOptions($$parsedSource as Partial<SaveFileOptions>);
    }
}

export class Screen {
    "isCurrent": boolean;
    "isPrimary": boolean;
    "width": number;
    "height": number;
    "physicalWidth": number;
    "physicalHeight": number;

    /** Creates a new Screen instance. */
    constructor($$source: Partial<Screen> = {}) {
        if (!("isCurrent" in $$source)) {
            this["isCurrent"] = false;
        }
        if (!("isPrimary" in $$source)) {
            this["isPrimary"] = false;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("physicalWidth" in $$source)) {
            this["physicalWidth"] = 0;
        }
        if (!("physicalHeight" in $$source)) {
            this["physicalHeight"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Screen instance from a string or object.
     */
    static createFrom($$source: any = {}): Screen {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Screen($$parsedSource as Partial<Screen>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = FileFilter.createFrom;
const $$createType2 = $Create.Array($$createType1);
