//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../cull-pear/internal/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notification$0 from "../../../../../cull-pear/internal/notification/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as singleinstance$0 from "../../../../../cull-pear/internal/singleinstance/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "app:second-instance": $$createType0,
        "native-kit:file-drop": $$createType1,
        "system-notification:activated": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = singleinstance$0.LaunchData.createFrom;
const $$createType1 = application$0.FileDrop.createFrom;
const $$createType2 = notification$0.Activation.createFrom;

configure();
