// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as application$0 from "../../../../../dn-wails/internal/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as notification$0 from "../../../../../dn-wails/internal/notification/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as singleinstance$0 from "../../../../../dn-wails/internal/singleinstance/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "app:second-instance": singleinstance$0.LaunchData;
            "native-kit:file-drop": application$0.FileDrop;
            "system-notification:activated": notification$0.Activation;
        }
    }
}
