// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppSettings {
    "version": number;
    "appearance": Appearance;
    "notifications": Notifications;
    "window": Window;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("appearance" in $$source)) {
            this["appearance"] = (new Appearance());
        }
        if (!("notifications" in $$source)) {
            this["notifications"] = (new Notifications());
        }
        if (!("window" in $$source)) {
            this["window"] = (new Window());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField1_0($$parsedSource["appearance"]);
        }
        if ("notifications" in $$parsedSource) {
            $$parsedSource["notifications"] = $$createField2_0($$parsedSource["notifications"]);
        }
        if ("window" in $$parsedSource) {
            $$parsedSource["window"] = $$createField3_0($$parsedSource["window"]);
        }
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

export class Appearance {
    "themeMode": string;
    "accent": string;
    "density": string;
    "buttonSize": string;
    "fontScale": number;

    /** Creates a new Appearance instance. */
    constructor($$source: Partial<Appearance> = {}) {
        if (!("themeMode" in $$source)) {
            this["themeMode"] = "";
        }
        if (!("accent" in $$source)) {
            this["accent"] = "";
        }
        if (!("density" in $$source)) {
            this["density"] = "";
        }
        if (!("buttonSize" in $$source)) {
            this["buttonSize"] = "";
        }
        if (!("fontScale" in $$source)) {
            this["fontScale"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Appearance instance from a string or object.
     */
    static createFrom($$source: any = {}): Appearance {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Appearance($$parsedSource as Partial<Appearance>);
    }
}

export class Notifications {
    "enabled": boolean;
    "showPreview": boolean;
    "doNotDisturb": boolean;

    /** Creates a new Notifications instance. */
    constructor($$source: Partial<Notifications> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("showPreview" in $$source)) {
            this["showPreview"] = false;
        }
        if (!("doNotDisturb" in $$source)) {
            this["doNotDisturb"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Notifications instance from a string or object.
     */
    static createFrom($$source: any = {}): Notifications {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Notifications($$parsedSource as Partial<Notifications>);
    }
}

export class Window {
    "closeBehavior": string;
    "alwaysOnTop": boolean;
    "rememberBounds": boolean;
    "bounds"?: WindowBounds | null;

    /** Creates a new Window instance. */
    constructor($$source: Partial<Window> = {}) {
        if (!("closeBehavior" in $$source)) {
            this["closeBehavior"] = "";
        }
        if (!("alwaysOnTop" in $$source)) {
            this["alwaysOnTop"] = false;
        }
        if (!("rememberBounds" in $$source)) {
            this["rememberBounds"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Window instance from a string or object.
     */
    static createFrom($$source: any = {}): Window {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bounds" in $$parsedSource) {
            $$parsedSource["bounds"] = $$createField3_0($$parsedSource["bounds"]);
        }
        return new Window($$parsedSource as Partial<Window>);
    }
}

export class WindowBounds {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "maximised": boolean;

    /** Creates a new WindowBounds instance. */
    constructor($$source: Partial<WindowBounds> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("maximised" in $$source)) {
            this["maximised"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowBounds instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowBounds {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowBounds($$parsedSource as Partial<WindowBounds>);
    }
}

// Private type creation functions
const $$createType0 = Appearance.createFrom;
const $$createType1 = Notifications.createFrom;
const $$createType2 = Window.createFrom;
const $$createType3 = WindowBounds.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
