// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails v3 service exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as account$0 from "../account/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appupdate$0 from "../appupdate/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dn$0 from "../dn/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dnprocess$0 from "../dnprocess/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nativekit$0 from "../nativekit/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as quicknotes$0 from "../quicknotes/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ChangePassword(input: account$0.PasswordInput): $CancellablePromise<void> {
    return $Call.ByID(2147315875, input);
}

export function CheckForApplicationUpdate(): $CancellablePromise<appupdate$0.Status> {
    return $Call.ByID(3766846992).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CheckOfficialSiteMessagesOnLogin(): $CancellablePromise<dn$0.OfficialMessageSyncResult> {
    return $Call.ByID(2793134418).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ClaimSiteMessageNotifications(limit: number): $CancellablePromise<dn$0.SiteMessageClaim> {
    return $Call.ByID(3510090936, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteDnRole(id: number): $CancellablePromise<dn$0.RoleProfession> {
    return $Call.ByID(4273763299, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function DeleteDnWeeklyPlan(id: number): $CancellablePromise<dn$0.WeeklyPlan> {
    return $Call.ByID(35026979, id).then(($result: any) => {
        return $$createType4($result);
    });
}

export function DeleteQuickNote(id: number): $CancellablePromise<void> {
    return $Call.ByID(3792362776, id);
}

export function DeleteSiteMessage(id: number): $CancellablePromise<dn$0.SiteMessage> {
    return $Call.ByID(2262305085, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetApplicationUpdateInfo(): $CancellablePromise<appupdate$0.Info> {
    return $Call.ByID(2795201645).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetAuthState(): $CancellablePromise<account$0.AuthState> {
    return $Call.ByID(4122867697).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetDiagnosticsInfo(): $CancellablePromise<$models.DiagnosticsInfo> {
    return $Call.ByID(1219397070).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetLifecycleStatus(): $CancellablePromise<$models.LifecycleStatus> {
    return $Call.ByID(3391808900).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetProfile(): $CancellablePromise<account$0.Profile> {
    return $Call.ByID(1031557003).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetRuntimeStatus(): $CancellablePromise<$models.RuntimeStatus> {
    return $Call.ByID(1798490416).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetScreens(): $CancellablePromise<nativekit$0.Screen[]> {
    return $Call.ByID(978621563).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetSettings(): $CancellablePromise<settings$0.AppSettings> {
    return $Call.ByID(2820910515).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GetSiteMessageInbox(limit: number): $CancellablePromise<dn$0.SiteMessageInbox> {
    return $Call.ByID(594247900, limit).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetSystemNotificationStatus(): $CancellablePromise<$models.SystemNotificationStatus> {
    return $Call.ByID(1607488410).then(($result: any) => {
        return $$createType16($result);
    });
}

export function ImportAvatar(path: string): $CancellablePromise<string> {
    return $Call.ByID(1794131966, path);
}

export function InitializeDnWeeklyPlans(): $CancellablePromise<dn$0.WeeklyPlanInitializationResult> {
    return $Call.ByID(3976834583).then(($result: any) => {
        return $$createType17($result);
    });
}

export function InstallApplicationUpdate(expectedVersion: string): $CancellablePromise<void> {
    return $Call.ByID(2918507696, expectedVersion);
}

export function KillDragonNestProcess(): $CancellablePromise<dnprocess$0.Info> {
    return $Call.ByID(3093591292).then(($result: any) => {
        return $$createType18($result);
    });
}

export function ListAllDnWeeklyPlans(): $CancellablePromise<dn$0.WeeklyPlan[]> {
    return $Call.ByID(3833714304).then(($result: any) => {
        return $$createType19($result);
    });
}

export function ListDnRoleOptions(): $CancellablePromise<dn$0.RoleProfession[]> {
    return $Call.ByID(3803055926).then(($result: any) => {
        return $$createType20($result);
    });
}

export function ListDnRoles(query: dn$0.RoleProfessionQuery): $CancellablePromise<dn$0.RoleProfessionList> {
    return $Call.ByID(1681849057, query).then(($result: any) => {
        return $$createType21($result);
    });
}

export function ListDnWeeklyPlans(query: dn$0.WeeklyPlanQuery): $CancellablePromise<dn$0.WeeklyPlanList> {
    return $Call.ByID(3984086525, query).then(($result: any) => {
        return $$createType22($result);
    });
}

export function ListDragonNestProcesses(): $CancellablePromise<dnprocess$0.Info[]> {
    return $Call.ByID(4218085744).then(($result: any) => {
        return $$createType23($result);
    });
}

export function ListQuickNotes(): $CancellablePromise<quicknotes$0.Note[]> {
    return $Call.ByID(3611448438).then(($result: any) => {
        return $$createType25($result);
    });
}

export function ListSiteMessages(query: dn$0.SiteMessageQuery): $CancellablePromise<dn$0.SiteMessageList> {
    return $Call.ByID(1907897541, query).then(($result: any) => {
        return $$createType26($result);
    });
}

export function LoginUser(input: account$0.LoginInput): $CancellablePromise<account$0.Profile> {
    return $Call.ByID(3476684652, input).then(($result: any) => {
        return $$createType10($result);
    });
}

export function LogoutUser(): $CancellablePromise<void> {
    return $Call.ByID(3907551175);
}

export function MarkAllSiteMessagesRead(): $CancellablePromise<number> {
    return $Call.ByID(2299050197);
}

export function MarkSiteMessageNotified(id: number): $CancellablePromise<void> {
    return $Call.ByID(1074730107, id);
}

export function MarkSiteMessageRead(id: number): $CancellablePromise<dn$0.SiteMessage> {
    return $Call.ByID(2030646531, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function OpenDiagnosticsDirectory(): $CancellablePromise<void> {
    return $Call.ByID(3059434425);
}

export function OpenDirectory(title: string, defaultDirectory: string): $CancellablePromise<string> {
    return $Call.ByID(1732963953, title, defaultDirectory);
}

export function OpenExternalURL(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(1508594666, rawURL);
}

export function OpenFiles(options: nativekit$0.OpenFilesOptions): $CancellablePromise<string[]> {
    return $Call.ByID(3716198309, options).then(($result: any) => {
        return $$createType27($result);
    });
}

export function PublishSiteMessage(input: dn$0.SiteMessageInput): $CancellablePromise<dn$0.SiteMessage> {
    return $Call.ByID(3773549537, input).then(($result: any) => {
        return $$createType5($result);
    });
}

export function QuitApplication(): $CancellablePromise<void> {
    return $Call.ByID(2573249417);
}

export function ReadClipboard(): $CancellablePromise<string> {
    return $Call.ByID(1708176524);
}

export function RegisterUser(input: account$0.RegistrationInput): $CancellablePromise<account$0.Profile> {
    return $Call.ByID(3035054512, input).then(($result: any) => {
        return $$createType10($result);
    });
}

export function RequestSystemNotificationPermission(): $CancellablePromise<boolean> {
    return $Call.ByID(1118054234);
}

export function RequestWindowClose(): $CancellablePromise<void> {
    return $Call.ByID(884993677);
}

export function ResetSettings(): $CancellablePromise<settings$0.AppSettings> {
    return $Call.ByID(3684332592).then(($result: any) => {
        return $$createType14($result);
    });
}

export function SaveDnRole(input: dn$0.RoleProfessionInput): $CancellablePromise<dn$0.RoleProfession> {
    return $Call.ByID(3736898233, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SaveDnWeeklyPlan(input: dn$0.WeeklyPlanInput): $CancellablePromise<dn$0.WeeklyPlan> {
    return $Call.ByID(2714302325, input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SaveFile(options: nativekit$0.SaveFileOptions): $CancellablePromise<string> {
    return $Call.ByID(960788009, options);
}

export function SaveQuickNote(input: quicknotes$0.NoteInput): $CancellablePromise<quicknotes$0.Note> {
    return $Call.ByID(542893622, input).then(($result: any) => {
        return $$createType24($result);
    });
}

export function SendMessageNotification(request: $models.MessageNotificationRequest): $CancellablePromise<string> {
    return $Call.ByID(1298638816, request);
}

export function ShowMessageDialog(options: nativekit$0.MessageDialogOptions): $CancellablePromise<string> {
    return $Call.ByID(23103822, options);
}

export function SyncDnWeeklyPlans(): $CancellablePromise<dn$0.WeeklyPlanSyncResult> {
    return $Call.ByID(3398052580).then(($result: any) => {
        return $$createType28($result);
    });
}

export function SyncOfficialSiteMessages(): $CancellablePromise<dn$0.OfficialMessageSyncResult> {
    return $Call.ByID(3990901871).then(($result: any) => {
        return $$createType1($result);
    });
}

export function TerminateDragonNestProcess(target: dnprocess$0.Target): $CancellablePromise<dnprocess$0.Info> {
    return $Call.ByID(79659205, target).then(($result: any) => {
        return $$createType18($result);
    });
}

export function UpdateProfile(input: account$0.ProfileInput): $CancellablePromise<account$0.Profile> {
    return $Call.ByID(1442719852, input).then(($result: any) => {
        return $$createType10($result);
    });
}

export function UpdateSettings(next: settings$0.AppSettings): $CancellablePromise<settings$0.AppSettings> {
    return $Call.ByID(2350933742, next).then(($result: any) => {
        return $$createType14($result);
    });
}

export function UpdateSiteMessage(id: number, input: dn$0.SiteMessageInput): $CancellablePromise<dn$0.SiteMessage> {
    return $Call.ByID(773693279, id, input).then(($result: any) => {
        return $$createType5($result);
    });
}

export function WriteClipboard(text: string): $CancellablePromise<void> {
    return $Call.ByID(2196179649, text);
}

// Private type creation functions
const $$createType0 = appupdate$0.Status.createFrom;
const $$createType1 = dn$0.OfficialMessageSyncResult.createFrom;
const $$createType2 = dn$0.SiteMessageClaim.createFrom;
const $$createType3 = dn$0.RoleProfession.createFrom;
const $$createType4 = dn$0.WeeklyPlan.createFrom;
const $$createType5 = dn$0.SiteMessage.createFrom;
const $$createType6 = appupdate$0.Info.createFrom;
const $$createType7 = account$0.AuthState.createFrom;
const $$createType8 = $models.DiagnosticsInfo.createFrom;
const $$createType9 = $models.LifecycleStatus.createFrom;
const $$createType10 = account$0.Profile.createFrom;
const $$createType11 = $models.RuntimeStatus.createFrom;
const $$createType12 = nativekit$0.Screen.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = settings$0.AppSettings.createFrom;
const $$createType15 = dn$0.SiteMessageInbox.createFrom;
const $$createType16 = $models.SystemNotificationStatus.createFrom;
const $$createType17 = dn$0.WeeklyPlanInitializationResult.createFrom;
const $$createType18 = dnprocess$0.Info.createFrom;
const $$createType19 = $Create.Array($$createType4);
const $$createType20 = $Create.Array($$createType3);
const $$createType21 = dn$0.RoleProfessionList.createFrom;
const $$createType22 = dn$0.WeeklyPlanList.createFrom;
const $$createType23 = $Create.Array($$createType18);
const $$createType24 = quicknotes$0.Note.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = dn$0.SiteMessageList.createFrom;
const $$createType27 = $Create.Array($Create.Any);
const $$createType28 = dn$0.WeeklyPlanSyncResult.createFrom;
