// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DiagnosticsInfo {
    "appName": string;
    "appVersion": string;
    "goVersion": string;
    "os": string;
    "arch": string;
    "startedAt": string;
    "logDirectory": string;
    "logFile": string;

    /** Creates a new DiagnosticsInfo instance. */
    constructor($$source: Partial<DiagnosticsInfo> = {}) {
        if (!("appName" in $$source)) {
            this["appName"] = "";
        }
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }
        if (!("goVersion" in $$source)) {
            this["goVersion"] = "";
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }
        if (!("logDirectory" in $$source)) {
            this["logDirectory"] = "";
        }
        if (!("logFile" in $$source)) {
            this["logFile"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticsInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DiagnosticsInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiagnosticsInfo($$parsedSource as Partial<DiagnosticsInfo>);
    }
}

export class FileDrop {
    "x": number;
    "y": number;
    "paths": string[];

    /** Creates a new FileDrop instance. */
    constructor($$source: Partial<FileDrop> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileDrop instance from a string or object.
     */
    static createFrom($$source: any = {}): FileDrop {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField2_0($$parsedSource["paths"]);
        }
        return new FileDrop($$parsedSource as Partial<FileDrop>);
    }
}

export class LifecycleStatus {
    "startedAt": string;
    "ready": boolean;
    "secondInstanceCount": number;

    /** Creates a new LifecycleStatus instance. */
    constructor($$source: Partial<LifecycleStatus> = {}) {
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }
        if (!("secondInstanceCount" in $$source)) {
            this["secondInstanceCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LifecycleStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): LifecycleStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LifecycleStatus($$parsedSource as Partial<LifecycleStatus>);
    }
}

export class MessageNotificationRequest {
    "id"?: string;
    "sender": string;
    "content": string;
    "conversationId"?: string;

    /** Creates a new MessageNotificationRequest instance. */
    constructor($$source: Partial<MessageNotificationRequest> = {}) {
        if (!("sender" in $$source)) {
            this["sender"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageNotificationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageNotificationRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageNotificationRequest($$parsedSource as Partial<MessageNotificationRequest>);
    }
}

export class RuntimeServiceStatus {
    "key": string;
    "label": string;
    "status": string;
    "detail": string;

    /** Creates a new RuntimeServiceStatus instance. */
    constructor($$source: Partial<RuntimeServiceStatus> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeServiceStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeServiceStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeServiceStatus($$parsedSource as Partial<RuntimeServiceStatus>);
    }
}

export class RuntimeStatus {
    "overall": string;
    "checkedAt": string;
    "startedAt": string;
    "uptimeSeconds": number;
    "ready": boolean;
    "secondInstanceCount": number;
    "appVersion": string;
    "goVersion": string;
    "os": string;
    "arch": string;
    "logDirectory": string;
    "logFile": string;
    "services": RuntimeServiceStatus[];

    /** Creates a new RuntimeStatus instance. */
    constructor($$source: Partial<RuntimeStatus> = {}) {
        if (!("overall" in $$source)) {
            this["overall"] = "";
        }
        if (!("checkedAt" in $$source)) {
            this["checkedAt"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }
        if (!("uptimeSeconds" in $$source)) {
            this["uptimeSeconds"] = 0;
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }
        if (!("secondInstanceCount" in $$source)) {
            this["secondInstanceCount"] = 0;
        }
        if (!("appVersion" in $$source)) {
            this["appVersion"] = "";
        }
        if (!("goVersion" in $$source)) {
            this["goVersion"] = "";
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("logDirectory" in $$source)) {
            this["logDirectory"] = "";
        }
        if (!("logFile" in $$source)) {
            this["logFile"] = "";
        }
        if (!("services" in $$source)) {
            this["services"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeStatus {
        const $$createField12_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("services" in $$parsedSource) {
            $$parsedSource["services"] = $$createField12_0($$parsedSource["services"]);
        }
        return new RuntimeStatus($$parsedSource as Partial<RuntimeStatus>);
    }
}

export class SystemNotificationStatus {
    "available": boolean;
    "authorized": boolean;

    /** Creates a new SystemNotificationStatus instance. */
    constructor($$source: Partial<SystemNotificationStatus> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("authorized" in $$source)) {
            this["authorized"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemNotificationStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemNotificationStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemNotificationStatus($$parsedSource as Partial<SystemNotificationStatus>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = RuntimeServiceStatus.createFrom;
const $$createType2 = $Create.Array($$createType1);
