// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Note {
    "id": number;
    "title": string;
    "content": string;
    "pinned": boolean;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Note instance. */
    constructor($$source: Partial<Note> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     */
    static createFrom($$source: any = {}): Note {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Note($$parsedSource as Partial<Note>);
    }
}

export class NoteInput {
    "id": number;
    "title": string;
    "content": string;
    "pinned": boolean;

    /** Creates a new NoteInput instance. */
    constructor($$source: Partial<NoteInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoteInput instance from a string or object.
     */
    static createFrom($$source: any = {}): NoteInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NoteInput($$parsedSource as Partial<NoteInput>);
    }
}
