// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ListMeta {
    "total": number;
    "totalPages": number;
    "page": number;
    "pageSize": number;

    /** Creates a new ListMeta instance. */
    constructor($$source: Partial<ListMeta> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): ListMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListMeta($$parsedSource as Partial<ListMeta>);
    }
}

export class OfficialMessageSyncResult {
    "skipped": boolean;
    "fetched": number;
    "published": number;
    "syncedAt": string;

    /** Creates a new OfficialMessageSyncResult instance. */
    constructor($$source: Partial<OfficialMessageSyncResult> = {}) {
        if (!("skipped" in $$source)) {
            this["skipped"] = false;
        }
        if (!("fetched" in $$source)) {
            this["fetched"] = 0;
        }
        if (!("published" in $$source)) {
            this["published"] = 0;
        }
        if (!("syncedAt" in $$source)) {
            this["syncedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OfficialMessageSyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): OfficialMessageSyncResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OfficialMessageSyncResult($$parsedSource as Partial<OfficialMessageSyncResult>);
    }
}

export class RoleProfession {
    "id": number;
    "ownerId": number;
    "roleName": string;
    "profession": string;
    "priority": number;
    "remark": string;
    "sortOrder": number;
    "weeklyPlanCount": number;
    "createdAt": string;
    "updatedAt": string;
    "deletedAt": string;

    /** Creates a new RoleProfession instance. */
    constructor($$source: Partial<RoleProfession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ownerId" in $$source)) {
            this["ownerId"] = 0;
        }
        if (!("roleName" in $$source)) {
            this["roleName"] = "";
        }
        if (!("profession" in $$source)) {
            this["profession"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("weeklyPlanCount" in $$source)) {
            this["weeklyPlanCount"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("deletedAt" in $$source)) {
            this["deletedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoleProfession instance from a string or object.
     */
    static createFrom($$source: any = {}): RoleProfession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoleProfession($$parsedSource as Partial<RoleProfession>);
    }
}

export class RoleProfessionInput {
    "id": number;
    "roleName": string;
    "profession": string;
    "priority": number;
    "remark": string;
    "sortOrder": number;

    /** Creates a new RoleProfessionInput instance. */
    constructor($$source: Partial<RoleProfessionInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("roleName" in $$source)) {
            this["roleName"] = "";
        }
        if (!("profession" in $$source)) {
            this["profession"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoleProfessionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): RoleProfessionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoleProfessionInput($$parsedSource as Partial<RoleProfessionInput>);
    }
}

export class RoleProfessionList {
    "items": RoleProfession[];
    "meta": ListMeta;

    /** Creates a new RoleProfessionList instance. */
    constructor($$source: Partial<RoleProfessionList> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("meta" in $$source)) {
            this["meta"] = (new ListMeta());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoleProfessionList instance from a string or object.
     */
    static createFrom($$source: any = {}): RoleProfessionList {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField1_0($$parsedSource["meta"]);
        }
        return new RoleProfessionList($$parsedSource as Partial<RoleProfessionList>);
    }
}

export class RoleProfessionQuery {
    "roleName": string;
    "profession": string;
    "priority": number;
    "page": number;
    "pageSize": number;

    /** Creates a new RoleProfessionQuery instance. */
    constructor($$source: Partial<RoleProfessionQuery> = {}) {
        if (!("roleName" in $$source)) {
            this["roleName"] = "";
        }
        if (!("profession" in $$source)) {
            this["profession"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoleProfessionQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): RoleProfessionQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoleProfessionQuery($$parsedSource as Partial<RoleProfessionQuery>);
    }
}

export class SiteMessage {
    "id": number;
    "source": string;
    "sourceKey": string;
    "level": string;
    "title": string;
    "content": string;
    "actionLabel": string;
    "actionUrl": string;
    "actionTarget": string;
    "popup": boolean;
    "status": number;
    "publishedAt": string;
    "expiresAt": string;
    "createdBy": number;
    "metadata"?: SiteMessageMetadata | null;
    "readAt"?: string;
    "isRead"?: boolean;

    /** Creates a new SiteMessage instance. */
    constructor($$source: Partial<SiteMessage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("sourceKey" in $$source)) {
            this["sourceKey"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("actionLabel" in $$source)) {
            this["actionLabel"] = "";
        }
        if (!("actionUrl" in $$source)) {
            this["actionUrl"] = "";
        }
        if (!("actionTarget" in $$source)) {
            this["actionTarget"] = "";
        }
        if (!("popup" in $$source)) {
            this["popup"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "";
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = "";
        }
        if (!("createdBy" in $$source)) {
            this["createdBy"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessage {
        const $$createField14_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField14_0($$parsedSource["metadata"]);
        }
        return new SiteMessage($$parsedSource as Partial<SiteMessage>);
    }
}

export class SiteMessageClaim {
    "items": SiteMessage[];

    /** Creates a new SiteMessageClaim instance. */
    constructor($$source: Partial<SiteMessageClaim> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessageClaim instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessageClaim {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new SiteMessageClaim($$parsedSource as Partial<SiteMessageClaim>);
    }
}

export class SiteMessageInbox {
    "items": SiteMessage[];
    "unreadCount": number;
    "lastSyncedAt": string;
    "syncError": string;

    /** Creates a new SiteMessageInbox instance. */
    constructor($$source: Partial<SiteMessageInbox> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("unreadCount" in $$source)) {
            this["unreadCount"] = 0;
        }
        if (!("lastSyncedAt" in $$source)) {
            this["lastSyncedAt"] = "";
        }
        if (!("syncError" in $$source)) {
            this["syncError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessageInbox instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessageInbox {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new SiteMessageInbox($$parsedSource as Partial<SiteMessageInbox>);
    }
}

export class SiteMessageInput {
    "level": string;
    "title": string;
    "content": string;
    "actionLabel": string;
    "actionUrl": string;
    "actionTarget": string;
    "popup": boolean;
    "publishedAt": string;
    "expiresAt": string;

    /** Creates a new SiteMessageInput instance. */
    constructor($$source: Partial<SiteMessageInput> = {}) {
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("actionLabel" in $$source)) {
            this["actionLabel"] = "";
        }
        if (!("actionUrl" in $$source)) {
            this["actionUrl"] = "";
        }
        if (!("actionTarget" in $$source)) {
            this["actionTarget"] = "";
        }
        if (!("popup" in $$source)) {
            this["popup"] = false;
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "";
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessageInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessageInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteMessageInput($$parsedSource as Partial<SiteMessageInput>);
    }
}

export class SiteMessageList {
    "items": SiteMessage[];
    "meta": ListMeta;
    "unreadCount": number;
    "lastSyncedAt": string;
    "syncError": string;

    /** Creates a new SiteMessageList instance. */
    constructor($$source: Partial<SiteMessageList> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("meta" in $$source)) {
            this["meta"] = (new ListMeta());
        }
        if (!("unreadCount" in $$source)) {
            this["unreadCount"] = 0;
        }
        if (!("lastSyncedAt" in $$source)) {
            this["lastSyncedAt"] = "";
        }
        if (!("syncError" in $$source)) {
            this["syncError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessageList instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessageList {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField1_0($$parsedSource["meta"]);
        }
        return new SiteMessageList($$parsedSource as Partial<SiteMessageList>);
    }
}

export class SiteMessageMetadata {
    "categoryCode": string;
    "isTop": boolean;
    "isHot": boolean;
    "sourceId": number;

    /** Creates a new SiteMessageMetadata instance. */
    constructor($$source: Partial<SiteMessageMetadata> = {}) {
        if (!("categoryCode" in $$source)) {
            this["categoryCode"] = "";
        }
        if (!("isTop" in $$source)) {
            this["isTop"] = false;
        }
        if (!("isHot" in $$source)) {
            this["isHot"] = false;
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessageMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessageMetadata {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteMessageMetadata($$parsedSource as Partial<SiteMessageMetadata>);
    }
}

export class SiteMessageQuery {
    "keyword": string;
    "readStatus": string;
    "page": number;
    "pageSize": number;
    "manage": boolean;

    /** Creates a new SiteMessageQuery instance. */
    constructor($$source: Partial<SiteMessageQuery> = {}) {
        if (!("keyword" in $$source)) {
            this["keyword"] = "";
        }
        if (!("readStatus" in $$source)) {
            this["readStatus"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("manage" in $$source)) {
            this["manage"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessageQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessageQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteMessageQuery($$parsedSource as Partial<SiteMessageQuery>);
    }
}

export class WeeklyPlan {
    "id": number;
    "ownerId": number;
    "roleName": string;
    "profession": string;
    "priority": number;
    "remainingCommissionCount": number;
    "hasInvasion": boolean;
    "hasArk": boolean;
    "hasNightmare": boolean;
    "remark": string;
    "sortOrder": number;
    "roleProfessionId": number;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new WeeklyPlan instance. */
    constructor($$source: Partial<WeeklyPlan> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ownerId" in $$source)) {
            this["ownerId"] = 0;
        }
        if (!("roleName" in $$source)) {
            this["roleName"] = "";
        }
        if (!("profession" in $$source)) {
            this["profession"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("remainingCommissionCount" in $$source)) {
            this["remainingCommissionCount"] = 0;
        }
        if (!("hasInvasion" in $$source)) {
            this["hasInvasion"] = false;
        }
        if (!("hasArk" in $$source)) {
            this["hasArk"] = false;
        }
        if (!("hasNightmare" in $$source)) {
            this["hasNightmare"] = false;
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("roleProfessionId" in $$source)) {
            this["roleProfessionId"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlan {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeeklyPlan($$parsedSource as Partial<WeeklyPlan>);
    }
}

export class WeeklyPlanInitializationResult {
    "count": number;
    "created": number;
    "updated": number;

    /** Creates a new WeeklyPlanInitializationResult instance. */
    constructor($$source: Partial<WeeklyPlanInitializationResult> = {}) {
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("updated" in $$source)) {
            this["updated"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlanInitializationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlanInitializationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeeklyPlanInitializationResult($$parsedSource as Partial<WeeklyPlanInitializationResult>);
    }
}

export class WeeklyPlanInput {
    "id": number;
    "roleProfessionId": number;
    "remainingCommissionCount": number;
    "hasInvasion": boolean;
    "hasArk": boolean;
    "hasNightmare": boolean;
    "remark": string;
    "sortOrder": number;

    /** Creates a new WeeklyPlanInput instance. */
    constructor($$source: Partial<WeeklyPlanInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("roleProfessionId" in $$source)) {
            this["roleProfessionId"] = 0;
        }
        if (!("remainingCommissionCount" in $$source)) {
            this["remainingCommissionCount"] = 0;
        }
        if (!("hasInvasion" in $$source)) {
            this["hasInvasion"] = false;
        }
        if (!("hasArk" in $$source)) {
            this["hasArk"] = false;
        }
        if (!("hasNightmare" in $$source)) {
            this["hasNightmare"] = false;
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlanInput instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlanInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeeklyPlanInput($$parsedSource as Partial<WeeklyPlanInput>);
    }
}

export class WeeklyPlanList {
    "items": WeeklyPlan[];
    "meta": ListMeta;

    /** Creates a new WeeklyPlanList instance. */
    constructor($$source: Partial<WeeklyPlanList> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("meta" in $$source)) {
            this["meta"] = (new ListMeta());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlanList instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlanList {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField1_0($$parsedSource["meta"]);
        }
        return new WeeklyPlanList($$parsedSource as Partial<WeeklyPlanList>);
    }
}

export class WeeklyPlanQuery {
    "roleName": string;
    "profession": string;
    "priority": number;
    "roleProfessionId": number;
    "page": number;
    "pageSize": number;

    /** Creates a new WeeklyPlanQuery instance. */
    constructor($$source: Partial<WeeklyPlanQuery> = {}) {
        if (!("roleName" in $$source)) {
            this["roleName"] = "";
        }
        if (!("profession" in $$source)) {
            this["profession"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("roleProfessionId" in $$source)) {
            this["roleProfessionId"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlanQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlanQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeeklyPlanQuery($$parsedSource as Partial<WeeklyPlanQuery>);
    }
}

export class WeeklyPlanSyncResult {
    "created": number;
    "total": number;

    /** Creates a new WeeklyPlanSyncResult instance. */
    constructor($$source: Partial<WeeklyPlanSyncResult> = {}) {
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlanSyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlanSyncResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeeklyPlanSyncResult($$parsedSource as Partial<WeeklyPlanSyncResult>);
    }
}

// Private type creation functions
const $$createType0 = RoleProfession.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ListMeta.createFrom;
const $$createType3 = SiteMessageMetadata.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = SiteMessage.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = WeeklyPlan.createFrom;
const $$createType8 = $Create.Array($$createType7);
