// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LaunchData {
    "arguments": string[];
    "workingDirectory": string;

    /** Creates a new LaunchData instance. */
    constructor($$source: Partial<LaunchData> = {}) {
        if (!("arguments" in $$source)) {
            this["arguments"] = [];
        }
        if (!("workingDirectory" in $$source)) {
            this["workingDirectory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchData instance from a string or object.
     */
    static createFrom($$source: any = {}): LaunchData {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("arguments" in $$parsedSource) {
            $$parsedSource["arguments"] = $$createField0_0($$parsedSource["arguments"]);
        }
        return new LaunchData($$parsedSource as Partial<LaunchData>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
