// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {nativekit} from '../models';
import {settings} from '../models';

export function GetDiagnosticsInfo():Promise<application.DiagnosticsInfo>;

export function GetLifecycleStatus():Promise<application.LifecycleStatus>;

export function GetScreens():Promise<Array<nativekit.Screen>>;

export function GetSettings():Promise<settings.AppSettings>;

export function GetSystemNotificationStatus():Promise<application.SystemNotificationStatus>;

export function Greet(arg1:string):Promise<string>;

export function OpenDiagnosticsDirectory():Promise<void>;

export function OpenDirectory(arg1:string,arg2:string):Promise<string>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenFiles(arg1:nativekit.OpenFilesOptions):Promise<Array<string>>;

export function QuitApplication():Promise<void>;

export function ReadClipboard():Promise<string>;

export function RequestSystemNotificationPermission():Promise<boolean>;

export function RequestWindowClose():Promise<void>;

export function ResetSettings():Promise<settings.AppSettings>;

export function SaveFile(arg1:nativekit.SaveFileOptions):Promise<string>;

export function SendMessageNotification(arg1:application.MessageNotificationRequest):Promise<string>;

export function ShowMessageDialog(arg1:nativekit.MessageDialogOptions):Promise<string>;

export function UpdateSettings(arg1:settings.AppSettings):Promise<settings.AppSettings>;

export function WriteClipboard(arg1:string):Promise<void>;
