// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dn} from '../models';
import {application} from '../models';
import {nativekit} from '../models';
import {settings} from '../models';

export function ChangeDnPassword(arg1:dn.PasswordInput):Promise<void>;

export function ClaimDnMessageNotifications(arg1:number):Promise<dn.SiteMessageClaim>;

export function DeleteDnRole(arg1:number):Promise<dn.RoleProfession>;

export function DeleteDnWeeklyPlan(arg1:number):Promise<dn.WeeklyPlan>;

export function GetDiagnosticsInfo():Promise<application.DiagnosticsInfo>;

export function GetDnAuthState():Promise<dn.AuthState>;

export function GetDnMessageInbox(arg1:number):Promise<dn.SiteMessageInbox>;

export function GetDnProfile():Promise<dn.Profile>;

export function GetLifecycleStatus():Promise<application.LifecycleStatus>;

export function GetScreens():Promise<Array<nativekit.Screen>>;

export function GetSettings():Promise<settings.AppSettings>;

export function GetSystemNotificationStatus():Promise<application.SystemNotificationStatus>;

export function ImportDnAvatar(arg1:string):Promise<string>;

export function InitializeDnWeeklyPlans():Promise<dn.WeeklyPlanInitializationResult>;

export function ListAllDnWeeklyPlans():Promise<Array<dn.WeeklyPlan>>;

export function ListDnMessages(arg1:dn.SiteMessageQuery):Promise<dn.SiteMessageList>;

export function ListDnRoleOptions():Promise<Array<dn.RoleProfession>>;

export function ListDnRoles(arg1:dn.RoleProfessionQuery):Promise<dn.RoleProfessionList>;

export function ListDnWeeklyPlans(arg1:dn.WeeklyPlanQuery):Promise<dn.WeeklyPlanList>;

export function LoginDnUser(arg1:dn.LoginInput):Promise<dn.Profile>;

export function LogoutDnUser():Promise<void>;

export function MarkAllDnMessagesRead():Promise<number>;

export function MarkDnMessageRead(arg1:number):Promise<dn.SiteMessage>;

export function OpenDiagnosticsDirectory():Promise<void>;

export function OpenDirectory(arg1:string,arg2:string):Promise<string>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenFiles(arg1:nativekit.OpenFilesOptions):Promise<Array<string>>;

export function PublishDnMessage(arg1:dn.SiteMessageInput):Promise<dn.SiteMessage>;

export function QuitApplication():Promise<void>;

export function ReadClipboard():Promise<string>;

export function RegisterDnUser(arg1:dn.RegistrationInput):Promise<dn.Profile>;

export function RequestSystemNotificationPermission():Promise<boolean>;

export function RequestWindowClose():Promise<void>;

export function ResetSettings():Promise<settings.AppSettings>;

export function SaveDnRole(arg1:dn.RoleProfessionInput):Promise<dn.RoleProfession>;

export function SaveDnWeeklyPlan(arg1:dn.WeeklyPlanInput):Promise<dn.WeeklyPlan>;

export function SaveFile(arg1:nativekit.SaveFileOptions):Promise<string>;

export function SendMessageNotification(arg1:application.MessageNotificationRequest):Promise<string>;

export function ShowMessageDialog(arg1:nativekit.MessageDialogOptions):Promise<string>;

export function SyncDnOfficialMessages():Promise<dn.OfficialMessageSyncResult>;

export function SyncDnWeeklyPlans():Promise<dn.WeeklyPlanSyncResult>;

export function UpdateDnProfile(arg1:dn.ProfileInput):Promise<dn.Profile>;

export function UpdateSettings(arg1:settings.AppSettings):Promise<settings.AppSettings>;

export function WriteClipboard(arg1:string):Promise<void>;
