// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeDnPassword(arg1) {
  return window['go']['application']['App']['ChangeDnPassword'](arg1);
}

export function ClaimDnMessageNotifications(arg1) {
  return window['go']['application']['App']['ClaimDnMessageNotifications'](arg1);
}

export function DeleteDnRole(arg1) {
  return window['go']['application']['App']['DeleteDnRole'](arg1);
}

export function DeleteDnWeeklyPlan(arg1) {
  return window['go']['application']['App']['DeleteDnWeeklyPlan'](arg1);
}

export function GetDiagnosticsInfo() {
  return window['go']['application']['App']['GetDiagnosticsInfo']();
}

export function GetDnAuthState() {
  return window['go']['application']['App']['GetDnAuthState']();
}

export function GetDnMessageInbox(arg1) {
  return window['go']['application']['App']['GetDnMessageInbox'](arg1);
}

export function GetDnProfile() {
  return window['go']['application']['App']['GetDnProfile']();
}

export function GetLifecycleStatus() {
  return window['go']['application']['App']['GetLifecycleStatus']();
}

export function GetScreens() {
  return window['go']['application']['App']['GetScreens']();
}

export function GetSettings() {
  return window['go']['application']['App']['GetSettings']();
}

export function GetSystemNotificationStatus() {
  return window['go']['application']['App']['GetSystemNotificationStatus']();
}

export function ImportDnAvatar(arg1) {
  return window['go']['application']['App']['ImportDnAvatar'](arg1);
}

export function InitializeDnWeeklyPlans() {
  return window['go']['application']['App']['InitializeDnWeeklyPlans']();
}

export function ListAllDnWeeklyPlans() {
  return window['go']['application']['App']['ListAllDnWeeklyPlans']();
}

export function ListDnMessages(arg1) {
  return window['go']['application']['App']['ListDnMessages'](arg1);
}

export function ListDnRoleOptions() {
  return window['go']['application']['App']['ListDnRoleOptions']();
}

export function ListDnRoles(arg1) {
  return window['go']['application']['App']['ListDnRoles'](arg1);
}

export function ListDnWeeklyPlans(arg1) {
  return window['go']['application']['App']['ListDnWeeklyPlans'](arg1);
}

export function LoginDnUser(arg1) {
  return window['go']['application']['App']['LoginDnUser'](arg1);
}

export function LogoutDnUser() {
  return window['go']['application']['App']['LogoutDnUser']();
}

export function MarkAllDnMessagesRead() {
  return window['go']['application']['App']['MarkAllDnMessagesRead']();
}

export function MarkDnMessageRead(arg1) {
  return window['go']['application']['App']['MarkDnMessageRead'](arg1);
}

export function OpenDiagnosticsDirectory() {
  return window['go']['application']['App']['OpenDiagnosticsDirectory']();
}

export function OpenDirectory(arg1, arg2) {
  return window['go']['application']['App']['OpenDirectory'](arg1, arg2);
}

export function OpenExternalURL(arg1) {
  return window['go']['application']['App']['OpenExternalURL'](arg1);
}

export function OpenFiles(arg1) {
  return window['go']['application']['App']['OpenFiles'](arg1);
}

export function PublishDnMessage(arg1) {
  return window['go']['application']['App']['PublishDnMessage'](arg1);
}

export function QuitApplication() {
  return window['go']['application']['App']['QuitApplication']();
}

export function ReadClipboard() {
  return window['go']['application']['App']['ReadClipboard']();
}

export function RegisterDnUser(arg1) {
  return window['go']['application']['App']['RegisterDnUser'](arg1);
}

export function RequestSystemNotificationPermission() {
  return window['go']['application']['App']['RequestSystemNotificationPermission']();
}

export function RequestWindowClose() {
  return window['go']['application']['App']['RequestWindowClose']();
}

export function ResetSettings() {
  return window['go']['application']['App']['ResetSettings']();
}

export function SaveDnRole(arg1) {
  return window['go']['application']['App']['SaveDnRole'](arg1);
}

export function SaveDnWeeklyPlan(arg1) {
  return window['go']['application']['App']['SaveDnWeeklyPlan'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['application']['App']['SaveFile'](arg1);
}

export function SendMessageNotification(arg1) {
  return window['go']['application']['App']['SendMessageNotification'](arg1);
}

export function ShowMessageDialog(arg1) {
  return window['go']['application']['App']['ShowMessageDialog'](arg1);
}

export function SyncDnOfficialMessages() {
  return window['go']['application']['App']['SyncDnOfficialMessages']();
}

export function SyncDnWeeklyPlans() {
  return window['go']['application']['App']['SyncDnWeeklyPlans']();
}

export function UpdateDnProfile(arg1) {
  return window['go']['application']['App']['UpdateDnProfile'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['application']['App']['UpdateSettings'](arg1);
}

export function WriteClipboard(arg1) {
  return window['go']['application']['App']['WriteClipboard'](arg1);
}
