// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDiagnosticsInfo() {
  return window['go']['application']['App']['GetDiagnosticsInfo']();
}

export function GetLifecycleStatus() {
  return window['go']['application']['App']['GetLifecycleStatus']();
}

export function GetScreens() {
  return window['go']['application']['App']['GetScreens']();
}

export function GetSettings() {
  return window['go']['application']['App']['GetSettings']();
}

export function GetSystemNotificationStatus() {
  return window['go']['application']['App']['GetSystemNotificationStatus']();
}

export function Greet(arg1) {
  return window['go']['application']['App']['Greet'](arg1);
}

export function OpenDiagnosticsDirectory() {
  return window['go']['application']['App']['OpenDiagnosticsDirectory']();
}

export function OpenDirectory(arg1, arg2) {
  return window['go']['application']['App']['OpenDirectory'](arg1, arg2);
}

export function OpenExternalURL(arg1) {
  return window['go']['application']['App']['OpenExternalURL'](arg1);
}

export function OpenFiles(arg1) {
  return window['go']['application']['App']['OpenFiles'](arg1);
}

export function QuitApplication() {
  return window['go']['application']['App']['QuitApplication']();
}

export function ReadClipboard() {
  return window['go']['application']['App']['ReadClipboard']();
}

export function RequestSystemNotificationPermission() {
  return window['go']['application']['App']['RequestSystemNotificationPermission']();
}

export function RequestWindowClose() {
  return window['go']['application']['App']['RequestWindowClose']();
}

export function ResetSettings() {
  return window['go']['application']['App']['ResetSettings']();
}

export function SaveFile(arg1) {
  return window['go']['application']['App']['SaveFile'](arg1);
}

export function SendMessageNotification(arg1) {
  return window['go']['application']['App']['SendMessageNotification'](arg1);
}

export function ShowMessageDialog(arg1) {
  return window['go']['application']['App']['ShowMessageDialog'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['application']['App']['UpdateSettings'](arg1);
}

export function WriteClipboard(arg1) {
  return window['go']['application']['App']['WriteClipboard'](arg1);
}
