// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AuthState {
    "authenticated": boolean;
    "user": Profile | null;

    /** Creates a new AuthState instance. */
    constructor($$source: Partial<AuthState> = {}) {
        if (!("authenticated" in $$source)) {
            this["authenticated"] = false;
        }
        if (!("user" in $$source)) {
            this["user"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthState instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthState {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField1_0($$parsedSource["user"]);
        }
        return new AuthState($$parsedSource as Partial<AuthState>);
    }
}

export class LoginInput {
    "login": string;
    "password": string;

    /** Creates a new LoginInput instance. */
    constructor($$source: Partial<LoginInput> = {}) {
        if (!("login" in $$source)) {
            this["login"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginInput instance from a string or object.
     */
    static createFrom($$source: any = {}): LoginInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoginInput($$parsedSource as Partial<LoginInput>);
    }
}

export class PasswordInput {
    "currentPassword": string;
    "newPassword": string;

    /** Creates a new PasswordInput instance. */
    constructor($$source: Partial<PasswordInput> = {}) {
        if (!("currentPassword" in $$source)) {
            this["currentPassword"] = "";
        }
        if (!("newPassword" in $$source)) {
            this["newPassword"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PasswordInput instance from a string or object.
     */
    static createFrom($$source: any = {}): PasswordInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PasswordInput($$parsedSource as Partial<PasswordInput>);
    }
}

export class Profile {
    "id": number;
    "account": string;
    "name": string;
    "email": string;
    "role": number;
    "status": number;
    "avatar": string;
    "createdAt": string;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("account" in $$source)) {
            this["account"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("avatar" in $$source)) {
            this["avatar"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Profile($$parsedSource as Partial<Profile>);
    }
}

export class ProfileInput {
    "name": string;
    "email": string;
    "avatar": string;

    /** Creates a new ProfileInput instance. */
    constructor($$source: Partial<ProfileInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("avatar" in $$source)) {
            this["avatar"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileInput($$parsedSource as Partial<ProfileInput>);
    }
}

export class RegistrationInput {
    "account": string;
    "email": string;
    "password": string;

    /** Creates a new RegistrationInput instance. */
    constructor($$source: Partial<RegistrationInput> = {}) {
        if (!("account" in $$source)) {
            this["account"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegistrationInput instance from a string or object.
     */
    static createFrom($$source: any = {}): RegistrationInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RegistrationInput($$parsedSource as Partial<RegistrationInput>);
    }
}

// Private type creation functions
const $$createType0 = Profile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
