// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AuthState {
    "authenticated": boolean;
    "user": Profile | null;
    "expiresAt": string;

    /** Creates a new AuthState instance. */
    constructor($$source: Partial<AuthState> = {}) {
        if (!("authenticated" in $$source)) {
            this["authenticated"] = false;
        }
        if (!("user" in $$source)) {
            this["user"] = null;
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthState instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthState {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField1_0($$parsedSource["user"]);
        }
        return new AuthState($$parsedSource as Partial<AuthState>);
    }
}

export class ListMeta {
    "total": number;
    "totalPages": number;
    "page": number;
    "pageSize": number;

    /** Creates a new ListMeta instance. */
    constructor($$source: Partial<ListMeta> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): ListMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListMeta($$parsedSource as Partial<ListMeta>);
    }
}

export class LoginInput {
    "login": string;
    "password": string;

    /** Creates a new LoginInput instance. */
    constructor($$source: Partial<LoginInput> = {}) {
        if (!("login" in $$source)) {
            this["login"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginInput instance from a string or object.
     */
    static createFrom($$source: any = {}): LoginInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoginInput($$parsedSource as Partial<LoginInput>);
    }
}

export class OfficialMessageSyncResult {
    "skipped": boolean;
    "fetched": number;
    "published": number;
    "syncedAt": string;

    /** Creates a new OfficialMessageSyncResult instance. */
    constructor($$source: Partial<OfficialMessageSyncResult> = {}) {
        if (!("skipped" in $$source)) {
            this["skipped"] = false;
        }
        if (!("fetched" in $$source)) {
            this["fetched"] = 0;
        }
        if (!("published" in $$source)) {
            this["published"] = 0;
        }
        if (!("syncedAt" in $$source)) {
            this["syncedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OfficialMessageSyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): OfficialMessageSyncResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OfficialMessageSyncResult($$parsedSource as Partial<OfficialMessageSyncResult>);
    }
}

export class PasswordInput {
    "currentPassword": string;
    "newPassword": string;

    /** Creates a new PasswordInput instance. */
    constructor($$source: Partial<PasswordInput> = {}) {
        if (!("currentPassword" in $$source)) {
            this["currentPassword"] = "";
        }
        if (!("newPassword" in $$source)) {
            this["newPassword"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PasswordInput instance from a string or object.
     */
    static createFrom($$source: any = {}): PasswordInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PasswordInput($$parsedSource as Partial<PasswordInput>);
    }
}

export class Profile {
    "id": number;
    "account": string;
    "name": string;
    "email": string;
    "role": number;
    "status": number;
    "avatar": string;
    "createdAt": string;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("account" in $$source)) {
            this["account"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("avatar" in $$source)) {
            this["avatar"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Profile($$parsedSource as Partial<Profile>);
    }
}

export class ProfileInput {
    "name": string;
    "email": string;
    "avatar": string;

    /** Creates a new ProfileInput instance. */
    constructor($$source: Partial<ProfileInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("avatar" in $$source)) {
            this["avatar"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileInput($$parsedSource as Partial<ProfileInput>);
    }
}

export class RegistrationInput {
    "account": string;
    "email": string;
    "password": string;

    /** Creates a new RegistrationInput instance. */
    constructor($$source: Partial<RegistrationInput> = {}) {
        if (!("account" in $$source)) {
            this["account"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegistrationInput instance from a string or object.
     */
    static createFrom($$source: any = {}): RegistrationInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RegistrationInput($$parsedSource as Partial<RegistrationInput>);
    }
}

export class RoleProfession {
    "id": number;
    "ownerId": number;
    "roleName": string;
    "profession": string;
    "priority": number;
    "remark": string;
    "sortOrder": number;
    "weeklyPlanCount": number;
    "createdAt": string;
    "updatedAt": string;
    "deletedAt": string;

    /** Creates a new RoleProfession instance. */
    constructor($$source: Partial<RoleProfession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ownerId" in $$source)) {
            this["ownerId"] = 0;
        }
        if (!("roleName" in $$source)) {
            this["roleName"] = "";
        }
        if (!("profession" in $$source)) {
            this["profession"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("weeklyPlanCount" in $$source)) {
            this["weeklyPlanCount"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("deletedAt" in $$source)) {
            this["deletedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoleProfession instance from a string or object.
     */
    static createFrom($$source: any = {}): RoleProfession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoleProfession($$parsedSource as Partial<RoleProfession>);
    }
}

export class RoleProfessionInput {
    "id": number;
    "roleName": string;
    "profession": string;
    "priority": number;
    "remark": string;
    "sortOrder": number;

    /** Creates a new RoleProfessionInput instance. */
    constructor($$source: Partial<RoleProfessionInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("roleName" in $$source)) {
            this["roleName"] = "";
        }
        if (!("profession" in $$source)) {
            this["profession"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoleProfessionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): RoleProfessionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoleProfessionInput($$parsedSource as Partial<RoleProfessionInput>);
    }
}

export class RoleProfessionList {
    "items": RoleProfession[];
    "meta": ListMeta;

    /** Creates a new RoleProfessionList instance. */
    constructor($$source: Partial<RoleProfessionList> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("meta" in $$source)) {
            this["meta"] = (new ListMeta());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoleProfessionList instance from a string or object.
     */
    static createFrom($$source: any = {}): RoleProfessionList {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField1_0($$parsedSource["meta"]);
        }
        return new RoleProfessionList($$parsedSource as Partial<RoleProfessionList>);
    }
}

export class RoleProfessionQuery {
    "roleName": string;
    "profession": string;
    "priority": number;
    "page": number;
    "pageSize": number;

    /** Creates a new RoleProfessionQuery instance. */
    constructor($$source: Partial<RoleProfessionQuery> = {}) {
        if (!("roleName" in $$source)) {
            this["roleName"] = "";
        }
        if (!("profession" in $$source)) {
            this["profession"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoleProfessionQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): RoleProfessionQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoleProfessionQuery($$parsedSource as Partial<RoleProfessionQuery>);
    }
}

export class SiteMessage {
    "id": number;
    "source": string;
    "sourceKey": string;
    "level": string;
    "title": string;
    "content": string;
    "actionLabel": string;
    "actionUrl": string;
    "actionTarget": string;
    "popup": boolean;
    "status": number;
    "publishedAt": string;
    "expiresAt": string;
    "createdBy": number;
    "metadata"?: SiteMessageMetadata | null;
    "readAt"?: string;
    "isRead"?: boolean;

    /** Creates a new SiteMessage instance. */
    constructor($$source: Partial<SiteMessage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("sourceKey" in $$source)) {
            this["sourceKey"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("actionLabel" in $$source)) {
            this["actionLabel"] = "";
        }
        if (!("actionUrl" in $$source)) {
            this["actionUrl"] = "";
        }
        if (!("actionTarget" in $$source)) {
            this["actionTarget"] = "";
        }
        if (!("popup" in $$source)) {
            this["popup"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "";
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = "";
        }
        if (!("createdBy" in $$source)) {
            this["createdBy"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessage {
        const $$createField14_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField14_0($$parsedSource["metadata"]);
        }
        return new SiteMessage($$parsedSource as Partial<SiteMessage>);
    }
}

export class SiteMessageClaim {
    "items": SiteMessage[];

    /** Creates a new SiteMessageClaim instance. */
    constructor($$source: Partial<SiteMessageClaim> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessageClaim instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessageClaim {
        const $$createField0_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new SiteMessageClaim($$parsedSource as Partial<SiteMessageClaim>);
    }
}

export class SiteMessageInbox {
    "items": SiteMessage[];
    "unreadCount": number;
    "lastSyncedAt": string;
    "syncError": string;

    /** Creates a new SiteMessageInbox instance. */
    constructor($$source: Partial<SiteMessageInbox> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("unreadCount" in $$source)) {
            this["unreadCount"] = 0;
        }
        if (!("lastSyncedAt" in $$source)) {
            this["lastSyncedAt"] = "";
        }
        if (!("syncError" in $$source)) {
            this["syncError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessageInbox instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessageInbox {
        const $$createField0_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new SiteMessageInbox($$parsedSource as Partial<SiteMessageInbox>);
    }
}

export class SiteMessageInput {
    "level": string;
    "title": string;
    "content": string;
    "actionLabel": string;
    "actionUrl": string;
    "actionTarget": string;
    "popup": boolean;
    "publishedAt": string;
    "expiresAt": string;

    /** Creates a new SiteMessageInput instance. */
    constructor($$source: Partial<SiteMessageInput> = {}) {
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("actionLabel" in $$source)) {
            this["actionLabel"] = "";
        }
        if (!("actionUrl" in $$source)) {
            this["actionUrl"] = "";
        }
        if (!("actionTarget" in $$source)) {
            this["actionTarget"] = "";
        }
        if (!("popup" in $$source)) {
            this["popup"] = false;
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "";
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessageInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessageInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteMessageInput($$parsedSource as Partial<SiteMessageInput>);
    }
}

export class SiteMessageList {
    "items": SiteMessage[];
    "meta": ListMeta;
    "unreadCount": number;
    "lastSyncedAt": string;
    "syncError": string;

    /** Creates a new SiteMessageList instance. */
    constructor($$source: Partial<SiteMessageList> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("meta" in $$source)) {
            this["meta"] = (new ListMeta());
        }
        if (!("unreadCount" in $$source)) {
            this["unreadCount"] = 0;
        }
        if (!("lastSyncedAt" in $$source)) {
            this["lastSyncedAt"] = "";
        }
        if (!("syncError" in $$source)) {
            this["syncError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessageList instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessageList {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField1_0($$parsedSource["meta"]);
        }
        return new SiteMessageList($$parsedSource as Partial<SiteMessageList>);
    }
}

export class SiteMessageMetadata {
    "categoryCode": string;
    "isTop": boolean;
    "isHot": boolean;
    "sourceId": number;

    /** Creates a new SiteMessageMetadata instance. */
    constructor($$source: Partial<SiteMessageMetadata> = {}) {
        if (!("categoryCode" in $$source)) {
            this["categoryCode"] = "";
        }
        if (!("isTop" in $$source)) {
            this["isTop"] = false;
        }
        if (!("isHot" in $$source)) {
            this["isHot"] = false;
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessageMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessageMetadata {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteMessageMetadata($$parsedSource as Partial<SiteMessageMetadata>);
    }
}

export class SiteMessageQuery {
    "keyword": string;
    "readStatus": string;
    "page": number;
    "pageSize": number;

    /** Creates a new SiteMessageQuery instance. */
    constructor($$source: Partial<SiteMessageQuery> = {}) {
        if (!("keyword" in $$source)) {
            this["keyword"] = "";
        }
        if (!("readStatus" in $$source)) {
            this["readStatus"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteMessageQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteMessageQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteMessageQuery($$parsedSource as Partial<SiteMessageQuery>);
    }
}

export class WeeklyPlan {
    "id": number;
    "ownerId": number;
    "roleName": string;
    "profession": string;
    "priority": number;
    "nestCommissions": WeeklyPlanCommission[];
    "nestTickets": WeeklyPlanTicket[];
    "levelCommissionCount": number;
    "hasInvasion": boolean;
    "hasArk": boolean;
    "hasNightmare": boolean;
    "remark": string;
    "sortOrder": number;
    "roleProfessionId": number;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new WeeklyPlan instance. */
    constructor($$source: Partial<WeeklyPlan> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ownerId" in $$source)) {
            this["ownerId"] = 0;
        }
        if (!("roleName" in $$source)) {
            this["roleName"] = "";
        }
        if (!("profession" in $$source)) {
            this["profession"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("nestCommissions" in $$source)) {
            this["nestCommissions"] = [];
        }
        if (!("nestTickets" in $$source)) {
            this["nestTickets"] = [];
        }
        if (!("levelCommissionCount" in $$source)) {
            this["levelCommissionCount"] = 0;
        }
        if (!("hasInvasion" in $$source)) {
            this["hasInvasion"] = false;
        }
        if (!("hasArk" in $$source)) {
            this["hasArk"] = false;
        }
        if (!("hasNightmare" in $$source)) {
            this["hasNightmare"] = false;
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("roleProfessionId" in $$source)) {
            this["roleProfessionId"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlan {
        const $$createField5_0 = $$createType10;
        const $$createField6_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nestCommissions" in $$parsedSource) {
            $$parsedSource["nestCommissions"] = $$createField5_0($$parsedSource["nestCommissions"]);
        }
        if ("nestTickets" in $$parsedSource) {
            $$parsedSource["nestTickets"] = $$createField6_0($$parsedSource["nestTickets"]);
        }
        return new WeeklyPlan($$parsedSource as Partial<WeeklyPlan>);
    }
}

export class WeeklyPlanCommission {
    "id": number;
    "completed": boolean;

    /** Creates a new WeeklyPlanCommission instance. */
    constructor($$source: Partial<WeeklyPlanCommission> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("completed" in $$source)) {
            this["completed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlanCommission instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlanCommission {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeeklyPlanCommission($$parsedSource as Partial<WeeklyPlanCommission>);
    }
}

export class WeeklyPlanInitializationResult {
    "count": number;
    "created": number;
    "updated": number;

    /** Creates a new WeeklyPlanInitializationResult instance. */
    constructor($$source: Partial<WeeklyPlanInitializationResult> = {}) {
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("updated" in $$source)) {
            this["updated"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlanInitializationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlanInitializationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeeklyPlanInitializationResult($$parsedSource as Partial<WeeklyPlanInitializationResult>);
    }
}

export class WeeklyPlanInput {
    "id": number;
    "roleProfessionId": number;
    "nestCommissions": WeeklyPlanCommission[];
    "nestTickets": WeeklyPlanTicket[];
    "levelCommissionCount": number;
    "hasInvasion": boolean;
    "hasArk": boolean;
    "hasNightmare": boolean;
    "remark": string;
    "sortOrder": number;

    /** Creates a new WeeklyPlanInput instance. */
    constructor($$source: Partial<WeeklyPlanInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("roleProfessionId" in $$source)) {
            this["roleProfessionId"] = 0;
        }
        if (!("nestCommissions" in $$source)) {
            this["nestCommissions"] = [];
        }
        if (!("nestTickets" in $$source)) {
            this["nestTickets"] = [];
        }
        if (!("levelCommissionCount" in $$source)) {
            this["levelCommissionCount"] = 0;
        }
        if (!("hasInvasion" in $$source)) {
            this["hasInvasion"] = false;
        }
        if (!("hasArk" in $$source)) {
            this["hasArk"] = false;
        }
        if (!("hasNightmare" in $$source)) {
            this["hasNightmare"] = false;
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlanInput instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlanInput {
        const $$createField2_0 = $$createType10;
        const $$createField3_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nestCommissions" in $$parsedSource) {
            $$parsedSource["nestCommissions"] = $$createField2_0($$parsedSource["nestCommissions"]);
        }
        if ("nestTickets" in $$parsedSource) {
            $$parsedSource["nestTickets"] = $$createField3_0($$parsedSource["nestTickets"]);
        }
        return new WeeklyPlanInput($$parsedSource as Partial<WeeklyPlanInput>);
    }
}

export class WeeklyPlanList {
    "items": WeeklyPlan[];
    "meta": ListMeta;

    /** Creates a new WeeklyPlanList instance. */
    constructor($$source: Partial<WeeklyPlanList> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("meta" in $$source)) {
            this["meta"] = (new ListMeta());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlanList instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlanList {
        const $$createField0_0 = $$createType14;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField1_0($$parsedSource["meta"]);
        }
        return new WeeklyPlanList($$parsedSource as Partial<WeeklyPlanList>);
    }
}

export class WeeklyPlanQuery {
    "roleName": string;
    "profession": string;
    "priority": number;
    "nestCommission": string;
    "roleProfessionId": number;
    "page": number;
    "pageSize": number;

    /** Creates a new WeeklyPlanQuery instance. */
    constructor($$source: Partial<WeeklyPlanQuery> = {}) {
        if (!("roleName" in $$source)) {
            this["roleName"] = "";
        }
        if (!("profession" in $$source)) {
            this["profession"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("nestCommission" in $$source)) {
            this["nestCommission"] = "";
        }
        if (!("roleProfessionId" in $$source)) {
            this["roleProfessionId"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlanQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlanQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeeklyPlanQuery($$parsedSource as Partial<WeeklyPlanQuery>);
    }
}

export class WeeklyPlanSyncResult {
    "created": number;
    "total": number;

    /** Creates a new WeeklyPlanSyncResult instance. */
    constructor($$source: Partial<WeeklyPlanSyncResult> = {}) {
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlanSyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlanSyncResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeeklyPlanSyncResult($$parsedSource as Partial<WeeklyPlanSyncResult>);
    }
}

export class WeeklyPlanTicket {
    "id": number;
    "expiresAt": string;

    /** Creates a new WeeklyPlanTicket instance. */
    constructor($$source: Partial<WeeklyPlanTicket> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WeeklyPlanTicket instance from a string or object.
     */
    static createFrom($$source: any = {}): WeeklyPlanTicket {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WeeklyPlanTicket($$parsedSource as Partial<WeeklyPlanTicket>);
    }
}

// Private type creation functions
const $$createType0 = Profile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = RoleProfession.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ListMeta.createFrom;
const $$createType5 = SiteMessageMetadata.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = SiteMessage.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = WeeklyPlanCommission.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = WeeklyPlanTicket.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = WeeklyPlan.createFrom;
const $$createType14 = $Create.Array($$createType13);
